### PR TITLE
[ci skip] [skip ci] [cf admin skip] ***NO_CI*** New maintainer

### PR DESCRIPTION
**Pull request by cgr71ii**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I'm adding myself as maintainer because I created a PR of the same recipe (https://github.com/conda-forge/staged-recipes/pull/19724; I didn't notice that already existed), and this feedstock seems that is not being maintained anymore. I'd like to maintain it and make the build success in order to this package be available in the conda repo. https://github.com/conda-forge/staged-recipes/pull/19724#issuecomment-1194538466 told me to create this PR. I also created issue #2, but didn't get any answer.

@conda-forge/core, could you approve this PR?

### CODE REVIEW

**Comment by dopplershift** [comment]
@conda-forge-admin, please rerender

**Comment by dopplershift** [comment]
Ok, building the rerender failed on Linux. I'll just merge this and let you sort out the rerender/build in another PR.

**Comment by cgr71ii** [comment]
Thank you, @dopplershift. I already created the [PR](https://github.com/conda-forge/uchardet-feedstock/pull/4) with the fixes. I still don't have write access to the repo, shouldn't I have them since I'm now on the maintainers list in the `meta.yaml` file?

**Comment by dopplershift** [comment]
@cgr71ii You should have received an invite, especially after #5 . Make sure you check your spam folder.

**Pull request merged**
